language: scala
jdk:
    - oraclejdk8
scala:
   - 2.11.8
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
   - npm install
   - node ./node_modules/bower/bin/bower install
   - node ./node_modules/gulp/bin/gulp
   - pwd
   - ls -al ./libs
   - mv -f ./libs ./app/assets
before_script:
   - node ./node_modules/karma/bin/karma start ./app/assets/karma.conf.js --log-level debug --single-run