sudo: required  
dist: trusty
language: scala
jdk:
    - oraclejdk8
scala:
   - 2.11.8
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start 
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
install:
   - npm install
   - node ./node_modules/bower/bin/bower install
   - node ./node_modules/gulp/bin/gulp
   - rm -rf ./app/assets/libs
   - mv -f ./libs ./app/assets
before_script:
   - node ./node_modules/karma/bin/karma start ./app/assets/karma.conf.js --log-level debug --single-run